version: "2"
services:
  db:
    extends:
      file: base.yml
      service: db
    ports:
      - "5436:5432"
  vendors:
    image: python:3.6
    working_dir: /django_project
    volumes:
      - ./django_project/vendors:/django_project/vendors
      - ./django_project/Requirements:/django_project/Requirements
    environment:
      PYTHONUSERBASE: /django_project/vendors
    command: pip install -r /django_project/Requirements/local.txt --user --upgrade

  django_project:
    extends:
      file: base.yml
      service: django_project
    build:
      args:
        - DJANGO_ENV=local
    command: python3.6 manage.py runserver 0.0.0.0:8000
    volumes: 
      - ./django_project:/django_project
    environment:
      PYTHONUSERBASE: /django_project/vendors
    stdin_open: true
    tty: true
    ports:
      - "8050:8000"
    depends_on:
      - db
volumes:
  db:
    external: true
