version: "2"
services:
  db:
    extends:
      file: base.yml
      service: db
    ports:
      - "5436:5432"
  vendors:
    image: python:3.6
    working_dir: /django_commerce
    volumes:
      - ./django_commerce/vendors:/django_commerce/vendors
      - ./django_commerce/Requirements:/django_commerce/Requirements
    environment:
      PYTHONUSERBASE: /django_commerce/vendors
    command: pip install -r /django_commerce/Requirements/production.txt --user --upgrade

  django_commerce:
    extends:
      file: base.yml
      service: django_commerce
    build:
      args:
        - DJANGO_ENV=production
    command: python3.6 manage.py runserver 0.0.0.0:8000
    volumes: 
      - ./django_commerce:/django_commerce
    environment:
      PYTHONUSERBASE: /django_commerce/vendors
    stdin_open: true
    tty: true
    ports:
      - "8050:8000"
    depends_on:
      - db
volumes:
  db:
    external: true
